config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  
  resources :users
  resources :categories
  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments
  end
  
  root 'posts#index'
  
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :content, presence: true, length: {minimum: 3, maximum: 10000000000000000} 
  #validates :categories, presence: true 
  
  has_many :post_categories
	has_many :categories , through: :post_categories
  has_many :comments
  belongs_to :user
  
  acts_as_votable
  
  mount_uploader :featureimage, FeatureimageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @categories = Category.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comment.post_id = @post.id
    @categories = Category.all
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :featureimage, category_ids: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= form.text_area :content, class: 'form-control', rows: '10' , placeholder: 'Start post...' %>
  </div>

  <div class="form-group">
    <%= form.label :featureimage, 'Post Featured Image' %>
    <%= form.file_field :featureimage, id: :featureimage, class: 'form-control-file'  %>
  </div>

  <div class="form-check">
   <%= form.collection_check_boxes :category_ids , Category.all, :id , :name do |cb| %>
			<% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
		<% end %>
  </div>
    
 

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_likes.html.erb
<div class=”likes” id=”likes_<%= post.id %>”>
  <%= display_likes post %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>



<div class="row">
  <div class="col-lg-8">
    <% @posts.each do |post| %>
  <div class="card mb-3 shadow-lg p-3 mb-5 bg-white rounded">
     <%= link_to image_tag(post.featureimage_url, class: 'card-img-top rounded'),post if post.featureimage.present? %>
      <div class="card-body">
        <p class="card-text"><small class="text-muted"><%= post.created_at.strftime("%b %d") + ' / ' + post.categories.pluck(:name).join(",") %></small></p>
        <h5 class="card-title"><%= link_to post.title, post %></h5>
        <p class="card-text"><%= sanitize(truncate(post.content, length: 50)) + "[..]" %></p>
        
      </div>
  </div>
 <% end %> 
  </div>
  
  <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <% @categories.each do |category| %>
                    <li>
                      <%= link_to category.name, category %></a>
                    </li>
                    <% end %>
                  </ul>
                </div>
                
              </div>
            </div>
          </div>
</div>
  
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <h1>New Post</h1>

    <%= render 'form', post: @post %>

  </div>
  
  <div class="col-md-2"></div>

</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4"><%= @post.title %></h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="#"><%= @post.user.firstname + ' ' + @post.user.lastname %></a> in <%= @post.categories.pluck(:name).join(",") if @post.categories.present? %>
          </p>

          <hr>

          <!-- Date/Time -->
          <p><%= @post.created_at.strftime("%b %d") %></p>

          <hr>

          <!-- Preview Image -->
          
          <%= image_tag(@post.featureimage_url, class: 'img-fluid rounded') if @post.featureimage.present? %>
   

          <hr>

          <!-- Post Content -->
          
          <p><%= simple_format(@post.content) %></p>
          
          <br/>          
          <% if current_user %>
            <%= link_to "Edit", edit_post_path, class: "btn btn-success" %>
            <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
          <% end %>

          <hr>
    
          <div class="card">
            <h3 class="card-header">Meet the Author</h3>
            <div class="card-body">
              <h3><%= @post.user.firstname + ' ' + @post.user.lastname %></h3>
              <p><%= @post.user.userbio %></p>
            </div>  
          </div>
          
          <hr>
    
          <!-- Comments Form -->
          <%= render 'comments/form' %>

          <% if @post.comments.any? %>
            <h5>Comments</h5>
            <%= render partial: 'comments/comment', collection: @post.comments.reverse %>
            
          <% end %>

          <!-- Comment with nested comments -->
         

        </div>
  
  <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <% @categories.each do |category| %>
                    <li>
                      <%= link_to category.name, category %></a>
                    </li>
                    <% end %>
                  </ul>
                </div>
                
              </div>
            </div>
          </div>
</div>
</div>