config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  
  resources :users
  resources :categories
  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments
  end
  
  root 'posts#index'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Betapress</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "BetaPRESS", root_path, class: "navbar-brand" %>
      
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Posts", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">New Post</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% Category.all.each do |category| %>
            <%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    
    <% if user_signed_in? %>
        <div class="dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Hello <%= current_user.firstname %>!
          </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "My Posts", "#", class: "dropdown-item" %>
              <%= link_to "My Account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          
        </div>
    </div>
  
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      <% end %>
  
  </nav>
    
    
    
    <div class="container">
      <%= yield %>  
    </div>
    
    
  </body>
</html>